### ISSUE TITLE
My bag: fields to narrow

### ISSUE THREAD

**Issue by bitstr3am** [PulseTick/PulseTickIOS#1]
The my bag input fields are too small. Need room for digits into the billions or higher for some folks I guess. Consider auto comma too.

The view on the main screen should show token count (commas) as well as the dollar value it shows now.

Off to a great start!

**Comment by PulseTick** [comment]
I’ve added an auto zoom in the new version. As the bag gets larger, the field zooms a litre. 

I’ll leave this one open as I need to implement the commas. Thanks for the feedback!

**Comment by PulseTick** [comment]
Portfolio is now tracked using public wallets and you can add up to 5.

Auto comma function has also been deployed and is working. 

v2 is much better than v1! Thanks for raising the issue and feel free to raise anything else.
